web/router.ex
defmodule Blog.Router do
  use Blog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Blog do
    pipe_through :browser

    get "/", PostController, :index

    resources "/posts", PostController do
      resources "/comments", CommentController, only: [:create]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Blog do
  #   pipe_through :api
  # end
end

lib/blog/endpoint.ex
defmodule Blog.Endpoint do
  use Phoenix.Endpoint, otp_app: :blog

  socket "/socket", Blog.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :blog, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_blog_key",
    signing_salt: "qUlU27eC"

  plug Blog.Router
end

lib/blog/repo.ex
defmodule Blog.Repo do
  use Ecto.Repo, otp_app: :blog
end

web/models/comment.ex
defmodule Blog.Comment do
  use Blog.Web, :model

  schema "comments" do
    field :body, :string
    belongs_to :post, Blog.Post

    timestamps
  end

  def changeset(struct, params) do
    struct
    |> cast(params, [:body, :post_id])
  end
end

web/models/post.ex
defmodule Blog.Post do
  use Blog.Web, :model

  alias Blog.Comment
  alias Blog.Repo

  schema "posts" do
    field :title, :string
    field :body, :string
    field :user_id, :integer
    field :short_description, :string

    has_many :comments, Blog.Comment

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body, :user_id, :short_description])
    # |> validate_required([:title, :body, :user_id])
  end

  def create_comment(struct, comment_params) do
    new_comment = %Comment{}
    |> Comment.changeset(Map.merge(comment_params, %{"post_id" => struct.id}))

    if Repo.insert(new_comment), do: {:ok, new_comment}, else: {:error, "Error"}
  end
end

web/controllers/comment_controller.ex
defmodule Blog.CommentController do
  use Blog.Web, :controller

  alias Blog.Repo
  alias Blog.Post

  def create(conn, %{"comment" => comment_params, "post_id" => post_id}) do
    post = Repo.get!(Post, post_id)

    case Post.create_comment(post, comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Saved! #{}")
        |> redirect(to: post_path(conn, :show, post))
      _ -> 
        conn
        |> text("Something really bad happened!!!")
    end
  end
end

web/controllers/page_controller.ex
defmodule Blog.PageController do
  use Blog.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/post_controller.ex
defmodule Blog.PostController do
  use Blog.Web, :controller

  alias Blog.Post
  alias Blog.Repo
  alias Blog.Comment

  def index(conn, _) do
    posts = Repo.all(Post)
    render conn, "index.html", posts: posts
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    |> Repo.preload(:comments)

    new_comment = Comment.changeset(%Comment{}, %{"post_id" => id})
    render conn, "show.html", post: post, comment: new_comment
  end

  def edit(conn, %{ "id" => id }) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post)
    render conn, "edit.html", post: post, changeset: changeset
  end

  def update(conn, %{"post" => post_params, "id" => id}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post, post_params)

    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Updated, brotha!")
        |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def new(conn, params) do
    changeset = Post.changeset(%Post{}, params)
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"post" => post_params}) do
    changeset = Post.changeset(%Post{}, post_params)

    case Repo.insert(changeset) do
      {:ok, elem} ->
        conn
        |> put_flash(:info, "Post has been created successfully!")
        |> redirect to: post_path(conn, :index)
      _ ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)

    Repo.delete!(post)

    conn
    |> put_flash(:info, "DELETED")
    |> redirect to: post_path(conn, :index)
  end
end

web/views/error_view.ex
defmodule Blog.ErrorView do
  use Blog.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Blog.LayoutView do
  use Blog.Web, :view
end

web/views/page_view.ex
defmodule Blog.PageView do
  use Blog.Web, :view
end

web/views/post_view.ex
defmodule Blog.PostView do
  use Blog.Web, :view

  def show_post_path(conn, post) do
    link post.title, to: post_path(conn, :show, post)
  end

  def new_post_button(conn) do
    link "New Post", to: post_path(conn, :new), class: 'btn btn-success btn-lg'
  end

  def no_comments_notification(conn, comments) do
    if Enum.count(comments) == 0, do: "Not a single comment is given yet.."
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <h2><%= link "Blog", to: post_path(@conn, :index) %></h2>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/post/edit.html.eex
<h3>Edit</h3>

<h2 id="title_preview"></h2>

<p id="short_description_preview"></p>

<p id="body_preview"></p>

<div class='jumbotron'>
  <%= form_for @changeset, post_path(@conn, :update, @post), fn f -> %>
    <%= text_input f, :title, class: 'form-control', placeholder: 'Title', id: 'title_draft' %>
    <br>

    <%= textarea f, :short_description, class: 'form-control', placeholder: 'Short description', id: 'short_description_draft' %>
    <br>

    <%= textarea f, :body, class: 'form-control', placeholder: 'Body', id: 'body_draft' %>
    <br>

    <a href="#" onclick="showDraft();" class='btn btn-success btn-lg'>Privew</a>
    <%= submit "Publish", class: 'btn btn-danger btn-lg' %>
  <% end %>
</div>


<script type="text/javascript">
// TODO: move to assets..
function showDraft() {
  ['title', 'short_description', 'body'].forEach(function(elem) {
    showElement(elem);
  });
}

function showElement(elem) {
  document.getElementById(elem + '_preview').innerHTML = getInputValue(elem);
}

function getInputValue(elem) {
  return document.getElementById(elem + '_draft').value;
}
</script>

web/templates/post/index.html.eex
<div class='row'>
  <div class='col-lg-12'>
    <%= new_post_button(@conn) %>

    <%= for post <- @posts do %>
      <h3><%= show_post_path(@conn, post) %></h3>
      <p><%= post.short_description %></p>
      <hr>
    <% end %>
  </div>
</div>

web/templates/post/new.html.eex
<div class="jumbotron">
  <h3>New Post</h3>

  <%= form_for @changeset, post_path(@conn, :create), fn f -> %>
    <%= text_input f, :title, class: 'form-control', placeholder: 'Title' %><br>
    <%= textarea f, :short_description, class: 'form-control', placeholder: 'Short description' %><br>
    <%= textarea f, :body, class: 'form-control', placeholder: 'Body' %><br>
    <%= submit "Publish", class: 'btn btn-success btn-lg' %>
  <% end %>
</div>

web/templates/post/show.html.eex
<div class='row'>
  <div class='col-lg-8'>
    <h2><%= @post.title %></h2>

    <p><%= @post.short_description %></p>

    <p><%= @post.body %></p>
  </div>

  <div class='col-lg-4'>
    <h4>Actions</h4>

    <ul>
      <li><%= link "Edit", to: post_path(@conn, :edit, @post) %></li>
      <li><%= link "Delete", to: post_path(@conn, :delete, @post), method: "delete" %></li>
    </ul>
  </div>
</div>

<div class='row'>
  <div class='col-lg-8'>
    <h2>Comments</h2>

    <%= form_for @comment, post_comment_path(@conn, :create, @post), fn f -> %>
      <%= textarea f, :body, class: 'form-control', placeholder: "Comment content" %><br>
      <%= submit "Submit", class: 'btn btn-success btn-xl' %>
    <% end %>

    <hr>

    <%= no_comments_notification(@conn, @post.comments) %>

    <%= for comment <- @post.comments do %>
      <h5>TODO: user</h5>
      <p><%= comment.body %></p>
      <hr>
    <% end %>
  </div>
</div>